version: "3"
services:
  mysql:
    build: ./mysql/
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/db:/var/lib/mysql
    image: mysql
    ports:
      - "127.0.0.1:3306:3306"
    container_name: "mysql-asayake"
    environment:
      - MYSQL_ROOT_PASSWORD=password
  
